"""baseline

Revision ID: 61bd79bcb065
Revises: 
Create Date: 2026-04-28 19:43:23.941505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bd79bcb065'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('details', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_fee_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_master_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('SITE_FEE', 'PASS_THROUGH', name='fixedfeekind'), nullable=False),
    sa.Column('sponsor_proposed', sa.Float(), nullable=True),
    sa.Column('site_default', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['fixed_fee_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('coverage_status', sa.Enum('QCT_COVERED', 'RESEARCH_REQUIRED', 'SHARED', name='coveragestatus'), nullable=False),
    sa.Column('cpt_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['price_master_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'code', 'name', name='uq_procedure_version_code_name')
    )
    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_code'), ['code'], unique=False)

    op.create_table('trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sponsor', sa.String(length=200), nullable=True),
    sa.Column('protocol_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'NEGOTIATING', 'AWARDED', 'ARCHIVED', name='trialstatus'), nullable=False),
    sa.Column('price_master_version_id', sa.Integer(), nullable=False),
    sa.Column('fixed_fee_template_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixed_fee_template_id'], ['fixed_fee_template.id'], ),
    sa.ForeignKeyConstraint(['price_master_version_id'], ['price_master_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id', 'round_number', name='uq_round_number')
    )
    op.create_table('procedure_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('medicare_rate', sa.Float(), nullable=True),
    sa.Column('amc_base_charge', sa.Float(), nullable=False),
    sa.Column('overhead_pct', sa.Float(), nullable=False),
    sa.Column('excluded_from_oh', sa.Boolean(), nullable=False),
    sa.Column('sponsor_share', sa.Float(), nullable=False),
    sa.Column('medicare_share', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_id')
    )
    op.create_table('trial_quantity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('visit_label', sa.String(length=100), nullable=False),
    sa.Column('enrolled_count', sa.Integer(), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id', 'visit_label', name='uq_trial_quantity_visit')
    )
    op.create_table('trial_soa_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('visit_label', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id', 'procedure_id', 'visit_label', name='uq_soa_cell')
    )
    op.create_table('budget_round_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=True),
    sa.Column('fixed_fee_id', sa.Integer(), nullable=True),
    sa.Column('new_amc_base_charge', sa.Float(), nullable=True),
    sa.Column('new_overhead_pct', sa.Float(), nullable=True),
    sa.Column('new_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['fixed_fee_id'], ['fixed_fee.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['budget_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_round_override')
    op.drop_table('trial_soa_cell')
    op.drop_table('trial_quantity')
    op.drop_table('procedure_price')
    op.drop_table('budget_round')
    op.drop_table('trial')
    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_code'))

    op.drop_table('procedure')
    op.drop_table('fixed_fee')
    op.drop_table('price_master_version')
    op.drop_table('fixed_fee_template')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
